// ============================================================================
// tb_lab_on_chip.sv — SystemVerilog Testbench for Lab-on-Chip Top
// ============================================================================
//
// This testbench demonstrates the hardware-software co-simulation
// described in the Simulation Plan (Sections 10, 13, 20):
//
//     Python biological model → virtual ADC stimulus files → RTL
//
// The testbench:
//     1. Loads optical ADC stimulus from .hex files (Python-generated)
//     2. Loads temperature ADC stimulus from .hex files
//     3. Drives them into the DUT (lab_on_chip_top)
//     4. Observes the FSM state, filtered signal, and final result
//     5. Dumps all signals to VCD for GTKWave visualisation
//
// Usage (Icarus Verilog):
//     iverilog -g2012 -o sim.vvp tb/tb_lab_on_chip.sv \
//         rtl/lab_on_chip_top.sv rtl/reaction_fsm.sv \
//         rtl/thermal_controller.sv rtl/optical_acquisition.sv \
//         rtl/digital_filter.sv rtl/baseline_estimator.sv \
//         rtl/decision_engine.sv
//     vvp sim.vvp
//     gtkwave tb/waveforms/sim.vcd
//
// The stimulus files are generated by:
//     python electronics/stimulus_generator.py
// ============================================================================

`timescale 1ns / 1ps

module tb_lab_on_chip;

    // ── Parameters ─────────────────────────────────────────────────────
    // Use a much faster clock for simulation speed.
    // Real system: 50 MHz. Testbench: scaled timers for tractable sim.
    localparam CLK_FREQ_HZ     = 50_000;     // 50 kHz (for fast sim)
    localparam DATA_WIDTH      = 12;
    localparam PWM_WIDTH       = 10;

    // Scaled-down timers (microseconds in real → cycles in sim)
    localparam PREHEAT_MS       = 30;         // 30 ms (was 30 s)
    localparam LAMP_MS          = 100;        // 100 ms (was 30 min)
    localparam TRANSFER_MS      = 10;         // 10 ms (was 5 s)
    localparam CRISPR_MS        = 80;         // 80 ms (was 15 min)
    localparam READ_INTERVAL_MS = 20;         // 20 ms (was 10 s)

    // ── Clock and reset ────────────────────────────────────────────────
    logic clk;
    logic rst_n;

    initial clk = 0;
    always #10_000 clk = ~clk;  // 50 kHz → 20 µs period

    // ── DUT signals ────────────────────────────────────────────────────
    logic                    btn_start;
    logic                    btn_abort;
    logic                    cartridge_in;
    logic [1:0]              class_mode;

    logic [DATA_WIDTH-1:0]   temp_adc_data;
    logic                    temp_adc_valid;

    logic [DATA_WIDTH-1:0]   optical_adc_data;
    logic                    optical_adc_valid;
    logic                    optical_adc_start;

    logic [PWM_WIDTH-1:0]    heater_pwm;
    logic                    led_en;

    logic [1:0]              result_code;
    logic                    result_ready;

    logic [3:0]              fsm_state;
    logic                    temp_valid;
    logic                    temp_fault;
    logic                    baseline_locked;
    logic                    fault;

    // ── DUT instantiation ──────────────────────────────────────────────
    lab_on_chip_top #(
        .DATA_WIDTH         (DATA_WIDTH),
        .PWM_WIDTH          (PWM_WIDTH),
        .CLK_FREQ_HZ        (CLK_FREQ_HZ),
        .FILTER_WINDOW_LOG2 (3),
        .BASELINE_LOG2      (4),
        .SETTLE_CYCLES      (5),        // fast settle for sim
        .PREHEAT_MS         (PREHEAT_MS),
        .LAMP_MS            (LAMP_MS),
        .TRANSFER_MS        (TRANSFER_MS),
        .CRISPR_MS          (CRISPR_MS),
        .READ_INTERVAL_MS   (READ_INTERVAL_MS),
        .THRESHOLD_POS      (12'd100),
        .THRESHOLD_NEG      (12'd20)
    ) dut (
        .clk             (clk),
        .rst_n           (rst_n),
        .btn_start       (btn_start),
        .btn_abort       (btn_abort),
        .cartridge_in    (cartridge_in),
        .class_mode      (class_mode),
        .temp_adc_data   (temp_adc_data),
        .temp_adc_valid  (temp_adc_valid),
        .optical_adc_data(optical_adc_data),
        .optical_adc_valid(optical_adc_valid),
        .optical_adc_start(optical_adc_start),
        .heater_pwm      (heater_pwm),
        .led_en          (led_en),
        .result_code     (result_code),
        .result_ready    (result_ready),
        .fsm_state       (fsm_state),
        .temp_valid      (temp_valid),
        .temp_fault      (temp_fault),
        .baseline_locked (baseline_locked),
        .fault           (fault)
    );

    // ── Stimulus memory ────────────────────────────────────────────────
    // Optical ADC stimulus loaded from Python-generated hex file
    localparam MAX_SAMPLES = 2048;
    logic [DATA_WIDTH-1:0] optical_stim [0:MAX_SAMPLES-1];
    logic [DATA_WIDTH-1:0] temp_stim    [0:MAX_SAMPLES-1];

    integer optical_idx;
    integer temp_idx;
    integer num_optical_samples;

    // ── Load stimulus files ────────────────────────────────────────────
    initial begin
        // Load optical ADC stimulus (positive test)
        $readmemh("tb/stimuli/positive/optical_adc.hex", optical_stim);
        // Load temperature stimulus
        $readmemh("tb/stimuli/positive/temp_adc.hex", temp_stim);

        $display("============================================================");
        $display("  HYBRID-LAB RTL Testbench");
        $display("  Stimulus loaded from Python biological model output");
        $display("============================================================");
    end

    // ── VCD dump ───────────────────────────────────────────────────────
    initial begin
        $dumpfile("tb/waveforms/sim.vcd");
        $dumpvars(0, tb_lab_on_chip);
    end

    // ── ADC response model ─────────────────────────────────────────────
    // When the DUT requests an ADC conversion (optical_adc_start),
    // we respond with the next stimulus sample after a small delay.
    always @(posedge clk) begin
        if (!rst_n) begin
            optical_adc_valid <= 1'b0;
            optical_adc_data  <= '0;
            optical_idx       <= 0;
        end else begin
            optical_adc_valid <= 1'b0;

            if (optical_adc_start) begin
                // Deliver sample on next clock
                optical_adc_data  <= optical_stim[optical_idx % MAX_SAMPLES];
                optical_adc_valid <= 1'b1;

                if (optical_idx < MAX_SAMPLES - 1)
                    optical_idx <= optical_idx + 1;
            end
        end
    end

    // ── Temperature ADC feed ───────────────────────────────────────────
    // Setpoint-tracking thermal model for testbench.
    //
    // Rather than simulating the full PID feedback loop (which requires
    // careful gain tuning for the sim timescale), this model directly
    // tracks the DUT's temperature setpoint with a first-order ramp.
    // This cleanly validates the FSM sequencing without PID tuning issues.
    //
    // Mapping: 0–4095 ADC codes ≈ 0–100 °C → ~40.95 codes/°C
    //          Ambient 25°C ≈ 1024,  LAMP 63°C ≈ 2583,  CRISPR 37°C ≈ 1516
    logic [3:0] temp_counter;
    logic signed [31:0] T_virtual;   // Q24.8 fixed-point
    logic signed [31:0] T_target;    // setpoint in Q24.8
    localparam AMBIENT_CODE_S = 32'sd1024;
    localparam RAMP_RATE      = 32'sd80;    // codes per update step (fast for sim)

    always @(posedge clk) begin
        if (!rst_n) begin
            temp_adc_valid <= 1'b0;
            temp_adc_data  <= 12'd1024;  // ambient
            temp_counter   <= '0;
            T_virtual      <= AMBIENT_CODE_S * 256;
        end else begin
            temp_adc_valid <= 1'b0;
            temp_counter   <= temp_counter + 1'b1;

            // Determine target: use FSM setpoint if nonzero, else ambient
            if (dut.fsm_temp_setpoint != '0)
                T_target <= $signed({20'b0, dut.fsm_temp_setpoint}) * 256;
            else
                T_target <= AMBIENT_CODE_S * 256;

            // Thermal dynamics: update every 10 clocks
            if (temp_counter == 4'd9) begin
                temp_counter <= '0;

                // Ramp toward target
                if (T_virtual < T_target - RAMP_RATE * 256)
                    T_virtual <= T_virtual + RAMP_RATE * 256;
                else if (T_virtual > T_target + RAMP_RATE * 256)
                    T_virtual <= T_virtual - RAMP_RATE * 256;
                else
                    T_virtual <= T_target;  // close enough → snap to target

                // Feed to DUT
                temp_adc_data  <= T_virtual[DATA_WIDTH+7:8];
                temp_adc_valid <= 1'b1;
            end
        end
    end



    // ── Result decoder ─────────────────────────────────────────────────
    function string decode_result(input logic [1:0] code);
        case (code)
            2'b00: return "NEGATIVE";
            2'b01: return "POSITIVE";
            2'b10: return "INDETERMINATE";
            2'b11: return "INVALID";
        endcase
    endfunction

    function string decode_state(input logic [3:0] code);
        case (code)
            4'd0: return "IDLE";
            4'd1: return "CARTRIDGE_CHECK";
            4'd2: return "PREHEAT";
            4'd3: return "LAMP";
            4'd4: return "TRANSFER";
            4'd5: return "CRISPR";
            4'd6: return "READ";
            4'd7: return "ANALYZE";
            4'd8: return "RESULT";
            4'd9: return "FAULT";
            default: return "UNKNOWN";
        endcase
    endfunction

    // ── State change monitor ───────────────────────────────────────────
    logic [3:0] prev_state;

    always @(posedge clk) begin
        if (fsm_state !== prev_state) begin
            $display("[%0t] FSM: %s → %s",
                     $time, decode_state(prev_state), decode_state(fsm_state));
            prev_state <= fsm_state;
        end
    end

    // ── Main test sequence ─────────────────────────────────────────────
    initial begin
        // Initialise
        rst_n        = 0;
        btn_start    = 0;
        btn_abort    = 0;
        cartridge_in = 0;
        class_mode   = 2'b00;  // simple threshold mode
        prev_state   = 4'd0;

        // Reset pulse
        repeat (5) @(posedge clk);
        rst_n = 1;
        $display("[%0t] Reset released", $time);

        // Wait a few clocks
        repeat (10) @(posedge clk);

        // ── Start the assay ────────────────────────────────────────
        $display("[%0t] Starting POSITIVE assay...", $time);
        btn_start = 1;
        @(posedge clk);
        btn_start = 0;

        // Simulate cartridge insertion after a short delay
        repeat (20) @(posedge clk);
        cartridge_in = 1;
        $display("[%0t] Cartridge inserted", $time);

        // ── Wait for result or timeout ─────────────────────────────
        fork
            begin
                // Wait for result
                wait (result_ready);
                $display("============================================================");
                $display("[%0t] RESULT: %s", $time, decode_result(result_code));
                $display("  Baseline locked: %0b", baseline_locked);
                $display("  Temperature valid: %0b", temp_valid);
                $display("  Fault: %0b", fault);
                $display("============================================================");
            end
            begin
                // Timeout (2 seconds — enough for full assay at sim clock)
                #2_000_000_000;
                $display("[%0t] TIMEOUT — simulation ended", $time);
            end
        join_any

        // Let signals settle
        repeat (100) @(posedge clk);

        $display("");
        $display("============================================================");
        $display("  Simulation complete.");
        $display("  View waveforms: gtkwave tb/waveforms/sim.vcd");
        $display("============================================================");
        $finish;
    end

endmodule
